
name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Wrangler
        run: npm install -g wrangler@3.90.0

      - name: Selective Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          # Check if only essential files changed
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          
          # Only deploy if worker.js or critical files changed
          if echo "$CHANGED_FILES" | grep -E '^(worker\.js|index\.html|css/|js/)'; then
            echo "Critical files changed, deploying..."
            wrangler deploy --minify
          else
            echo "No critical files changed, skipping deploy"
            exit 0
          fi

      - name: Handle Deploy Error
        if: failure()
        run: |
          echo "Deployment failed. This might be due to KV usage limits."
          echo "Options:"
          echo "1. Wait for daily limit reset"
          echo "2. Clean up unnecessary KV entries"
          echo "3. Upgrade Cloudflare plan"
