name: Deploy Jekyll dengan Header Keamanan

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      
      - name: Create _headers file
        run: |
          # Membuat file _headers dengan format yang benar
          echo "/*" > _site/_headers
          echo "  Content-Security-Policy: default-src 'self' *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; frame-ancestors 'self'; style-src 'self' 'unsafe-inline' *; img-src 'self' data: blob: *; font-src 'self' *; connect-src 'self' *; media-src 'self' *; frame-src 'self' *; worker-src 'self' blob: *; form-action 'self' *" >> _site/_headers
          echo "  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload" >> _site/_headers
          echo "  Cross-Origin-Opener-Policy: same-origin" >> _site/_headers
          echo "  X-Frame-Options: DENY" >> _site/_headers
          echo "  X-Content-Type-Options: nosniff" >> _site/_headers
          echo "  Referrer-Policy: strict-origin-when-cross-origin" >> _site/_headers
          echo "  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=()" >> _site/_headers
      
      - name: Verify _headers file
        run: |
          cat _site/_headers
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
