name: Deploy Jekyll Site with Security Headers

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1 # Older version of Ruby setup
        with:
          ruby-version: '2.7' # Use older Ruby version
          
      - name: Fix Gemfile
        run: |
          # Create basic Gemfile if needed
          if [ ! -f "Gemfile" ]; then
            echo "source 'https://rubygems.org'" > Gemfile
            echo "gem 'jekyll', '~> 4.1'" >> Gemfile
          fi
          # Remove problematic gemspec if exists
          rm -f *.gemspec || true
          
      - name: Install dependencies
        run: |
          gem install bundler -v '~> 2.1'
          bundle install

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --destination ./_site

      - name: Create _headers file
        run: |
          mkdir -p _site
          cat << 'EOF' > _site/_headers
          /*
            Content-Security-Policy: default-src 'self' *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; frame-ancestors 'self'; style-src 'self' 'unsafe-inline' *; img-src 'self' data: blob: *; font-src 'self' *; connect-src 'self' *; media-src 'self' *; frame-src 'self' *; worker-src 'self' blob: *; form-action 'self' *
            Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
            Cross-Origin-Opener-Policy: same-origin
            X-Frame-Options: DENY
            X-Content-Type-Options: nosniff
            Referrer-Policy: strict-origin-when-cross-origin
            Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=()
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2 # Alternative deployment action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
