name: Deploy GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.6
          bundler-cache: true
          
      - name: Install dependencies
        run: gem install jekyll-content-security-policy-generator
        
      - name: Build dependencies
        run: bundle install

      - name: Cek Path Gem
        run: bundle show --paths | grep jekyll-content-security-policy-generator || echo "Gem tidak ditemukan"

      - name: Debug Gem Files
        run: ls -R $(bundle show jekyll-content-security-policy-generator)

      - name: Generate Content Security Policy
        run: ruby -r jekyll-content-security-policy-generator -e 'puts "Gem Loaded Successfully"'

      - name: Build Jekyll site
        run: JEKYLL_ENV=production bundle exec jekyll build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
