name: Ruby Gem
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.6'

      - name: Remove Old Files and Create New Structure
        run: |
          # Hapus semua file lama yang bisa menyebabkan error
          rm -rf lib hbd.gemspec Gemfile README.md LICENSE.txt

          # Buat direktori baru
          mkdir -p lib/hbd/assets/javascripts

          # Buat file version.rb
          echo 'module HBD
            VERSION = "0.1.0"
          end' > lib/hbd/version.rb

          # Buat file utama HBD
          echo 'require_relative "hbd/version"

          module HBD
            class Error < StandardError; end
            
            def self.root
              File.expand_path "../..", __FILE__
            end
            
            def self.assets_path
              File.join root, "assets"
            end
          end' > lib/hbd.rb

          # Buat fireworks.js
          echo 'let fireworks = [];
          let gravity;

          function setup() {
            createCanvas(windowWidth, windowHeight);
            colorMode(HSB);
            gravity = createVector(0, 0.2);
            stroke(255);
            strokeWeight(4);
            background(0);
          }

          function draw() {
            colorMode(RGB);
            background(0, 0, 0, 25);
            
            if (random(1) < 0.05) {
              fireworks.push(new Firework());
            }
            
            for (let i = fireworks.length - 1; i >= 0; i--) {
              fireworks[i].update();
              fireworks[i].show();
              
              if (fireworks[i].done()) {
                fireworks.splice(i, 1);
              }
            }
          }' > lib/hbd/assets/javascripts/fireworks.js

          # Buat hbd.gemspec
          echo '# frozen_string_literal: true

          require_relative "lib/hbd/version"

          Gem::Specification.new do |spec|
            spec.name = "hbd"
            spec.version = HBD::VERSION
            spec.authors = ["${{ github.actor }}"]
            spec.email = ["${{ github.actor }}@users.noreply.github.com"]

            spec.summary = "HBD Animation with Fireworks"
            spec.description = "A Ruby gem that provides birthday fireworks animation"
            spec.homepage = "https://github.com/${{ github.repository }}"
            spec.license = "MIT"
            spec.required_ruby_version = ">= 3.1.0"

            spec.metadata["homepage_uri"] = spec.homepage
            spec.metadata["source_code_uri"] = spec.homepage

            spec.files = Dir["lib/**/*", "README.md", "LICENSE.txt"]
            spec.require_paths = ["lib"]

            spec.add_development_dependency "rake", "~> 13.0"
            spec.add_development_dependency "rspec", "~> 3.0"
          end' > hbd.gemspec

          # Buat Gemfile
          echo 'source "https://rubygems.org"
          gemspec' > Gemfile

          # Buat README.md
          echo '# HBD Gem

          Ruby gem for birthday animation.

          ## Installation

          ```ruby
          source "https://rubygems.pkg.github.com/${{ github.repository_owner }}" do
            gem "hbd"
          end
          ```

          ## Usage

          Add to your HTML:

          ```html
          <!doctype html><html lang="id" xml-lang="id"><head><meta charset="UTF-8"><title>Selamat Ulang Tahun!</title><link rel="shortcut icon" href="https://4211421036.github.io/g4lihru/987654567.png" type="image/x-icon"><link rel="icon" href="https://4211421036.github.io/g4lihru/987654567.png" type="image/x-icon"><link rel="preload" as="audio" href="https://4211421036.github.io/hbd/hbd.mp3"><link rel="preload" as="image" href="https://4211421036.github.io/hbd/hbd.jpg" type="image/jpg"><link rel="preload" as="image" href="https://4211421036.github.io/g4lihru/987654567.png" type="image/x-icon"><link rel="apple-touch-icon" href="https://4211421036.github.io/g4lihru/987654567.png"><link rel="canonical" href="https://4211421036.github.io/hbd/"><link rel="manifest" href="manifest.webmanifest" crossorigin="use-credentials"><meta name="application-name" content="HBD"><meta name="description" content="Selamat Ulang Tahun!"><meta name="generator" content="HBD"><meta name="bingbot" content="noarchive"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="keywords" content="Selamat Ulang Tahun!"><meta name="robots" content="index, follow"><meta name="author" content="GALIH RIDHO UTOMO"><meta name="color-scheme" content="dark light"><meta name="theme-color" media="(prefers-color-scheme: light)" content="#edf4f8"><meta name="theme-color" media="(prefers-color-scheme: dark)" content="#1e1e1e"><meta prefix="og: http://ogp.me/ns#" property="og:title" content="Selamat Ulang Tahun!"><meta prefix="og: http://ogp.me/ns#" property="og:type" content="website"><meta prefix="og: http://ogp.me/ns#" property="og:description" content="Selamat Ulang Tahun!"><meta prefix="og: http://ogp.me/ns#" property="og:site_name" content="Birthday Celebration"><meta prefix="og: http://ogp.me/ns#" property="og:locale" content="id_ID"><meta prefix="og: http://ogp.me/ns#" property="og:url" content="https://4211421036.github.io/hbd/"><meta prefix="og: http://ogp.me/ns#" property="og:image" content="https://4211421036.github.io/hbd/hbd.jpg"><meta prefix="og: http://ogp.me/ns#" property="og:image:secure_url" content="https://4211421036.github.io/hbd/hbd.jpg"><meta prefix="og: http://ogp.me/ns#" property="og:image:type" content="image/jpeg"><meta prefix="og: http://ogp.me/ns#" property="og:image:width" content="1280"><meta prefix="og: http://ogp.me/ns#" property="og:image:height" content="1280"><meta prefix="og: http://ogp.me/ns#" property="og:image:alt" content="Selamat Ulang Tahun"><meta prefix="og: http://ogp.me/ns#" property="og:audio:secure_url" content="https://4211421036.github.io/hbd/hbd.mp3"><meta prefix="og: http://ogp.me/ns#" property="og:audio" content="https://4211421036.github.io/hbd/hbd.mp3"><meta prefix="og: http://ogp.me/ns#" property="og:audio:type" content="audio/mpeg"><meta name="google-site-verification" content="OYdjPwgIjGMAbQd3CGwM_l20jLNRRp84mEl3kw06DMg"><meta name="browsermode" content="no-sensors"><meta name="renderer" content="webkit|ie-comp|ie-stand"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="mobile-web-app-capable" content="yes"><meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"><meta http-equiv="Pragma" content="no-cache"><meta http-equiv="Strict-Transport-Security" content="max-age=31536000; includeSubDomains; preload"><meta http-equiv="Cross-Origin-Opener-Policy" content="same-origin"><meta http-equiv="X-Content-Type-Options" content="nosniff"><meta http-equiv="Referrer-Policy" content="strict-origin"><meta http-equiv="Content-Security-Policy" content="style-src 'self' 'nonce-HhAt8acqxJncfl1zuPdmPQ==' 'unsafe-inline' https://4211421036.github.io http://4211421036.github.io; object-src 'none'; base-uri 'self'; img-src 'self' data: https://4211421036.github.io http://4211421036.github.io; default-src 'self' https://4211421036.github.io http://4211421036.github.io; script-src 'self' 'unsafe-inline' 'nonce-HhAt8acqxJncfl1zuPdmPQ==' 'strict-dynamic' 'sha384-oC5xZuayjRS/uax42oWTtZprJ3hCwfez8lJZtc0o0ZFSXFSPiTZhvRM7lkCzIE3g' 'sha384-8qhZECEumeO9WOzyEYb5gr73cuUk9ld2zhRe5Ki/sysPTiTeeAMR23/YLcdLSDtr' 'sha384-pQqoOFthVCMylNYJ0GyFMb4dBC/qyE3q/5wDxDKyjxqQpaLEFQjxiFmmlV6guegT' https://4211421036.github.io http://4211421036.github.io;; font-src 'self' https://4211421036.github.io http://4211421036.github.io; media-src 'self' https://4211421036.github.io http://4211421036.github.io; connect-src 'self' https://4211421036.github.io http://4211421036.github.io; form-action 'self'; manifest-src 'self' https://4211421036.github.io http://4211421036.github.io; worker-src 'self' blob: https://4211421036.github.io http://4211421036.github.io"><meta http-equiv="Expires" content="0"><meta http-equiv="content-language" content="id"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content="@ITBGRU"><meta name="twitter:creator" content="@ITBGRU"><meta name="twitter:title" content="Selamat Ulang Tahun"><meta name="twitter:description" content="Selamat Ulang Tahun"><meta name="twitter:image" content="https://4211421036.github.io/hbd/hbd.jpg"><meta name="twitter:domain" content="4211421036.github.io"><meta name="twitter:url" content="https://4211421036.github.io/MentalHealth"><meta name="twitter:image:src" content="https://4211421036.github.io/g4lihru/987654567.png"><meta name="twitter:image:alt" content="Mental Health">
          <script rel="preload" as="script" src="126693cc.js" nonce="HhAt8acqxJncfl1zuPdmPQ==" integrity="sha384-oC5xZuayjRS/uax42oWTtZprJ3hCwfez8lJZtc0o0ZFSXFSPiTZhvRM7lkCzIE3g" crossorigin="anonymous" defer="defer"></script><script rel="preload" as="script" src="e85802e3.js" nonce="HhAt8acqxJncfl1zuPdmPQ==" integrity="sha384-8qhZECEumeO9WOzyEYb5gr73cuUk9ld2zhRe5Ki/sysPTiTeeAMR23/YLcdLSDtr" crossorigin="anonymous" defer="defer"></script><script rel="preload" as="script" src="58fcdf02.js" nonce="HhAt8acqxJncfl1zuPdmPQ==" integrity="sha384-pQqoOFthVCMylNYJ0GyFMb4dBC/qyE3q/5wDxDKyjxqQpaLEFQjxiFmmlV6guegT" crossorigin="anonymous" defer="defer"></script><style nonce="HhAt8acqxJncfl1zuPdmPQ==">:root{--background:radial-gradient(100% 193.51% at 100% 0%, rgb(237, 244, 248) 0%, rgb(239, 242, 250) 16.92%, rgb(250, 239, 246) 34.8%, rgb(250, 230, 242) 48.8%, rgb(250, 240, 247) 63.79%, rgb(241, 241, 251) 81.34%, rgb(240, 244, 248) 100%);--text-light:#333333;--input-border-light:#dddddd;--input-bg-light:#ffffff;--placeholder-light:rgba(255,255,255,0.5);--background-dark:#1e1e1e;--text-dark:#ffffff;--input-border-dark:#404040;--input-bg-dark:#2d2d2d;--placeholder-dark:rgba(0,0,0,0.5);--transition-speed:0.3s}@media (prefers-color-scheme:dark){:root{color-scheme:dark;--background:var(--background-dark);--text:var(--text-dark);--input-border:var(--input-border-dark);--input-bg:var(--input-bg-dark);--placeholder:var(--placeholder-dark)}}@media (prefers-color-scheme:light){:root{color-scheme:light;--background:var(--background-light);--text:var(--text-light);--input-border:var(--input-border-light);--input-bg:var(--input-bg-light);--placeholder:var(--placeholder-light)}}body{margin:0;overflow:hidden;background:var(--background);color:var(--text)}@media (prefers-color-scheme:dark){body{background:var(--background);color:var(--text)}}@keyframes skeletonLoading{0%{opacity:.7}50%{opacity:.5}100%{opacity:.7}}.skeleton-animation{animation:skeletonLoading 1.5s infinite}// Di dalam bagian style input[type=text i]::placeholder{color:var(--placeholder);opacity:.1;transition:opacity var(--transition-speed) ease;contain:style layout;content-visibility:auto;font-display:swap}input#placeholder::-webkit-input-placeholder{display:none!important;color:transparent}input[type=text i]:focus::placeholder{opacity:.7}input[type=text i]:focus{outline:0;border-color:var(--button-bg);box-shadow:0 0 0 2px rgba(76,175,80,.2)}@media (prefers-reduced-motion:reduce){*{animation-duration:0s!important;animation-iteration-count:1!important;transition-duration:0s!important;scroll-behavior:auto!important}}</style></head><body translate="no" data-new-gr-c-s-check-loaded="14.1147.0"><script nonce="HhAt8acqxJncfl1zuPdmPQ==">"serviceWorker"in navigator&&navigator.serviceWorker.register("/hbd/sw.js").then(e=>console.log("Service worker registered")).catch(e=>console.log("Service worker not registered",e)),console.log("Generated automatic on: 2/15/2025, 12:28:51 AM")</script><script nonce="HhAt8acqxJncfl1zuPdmPQ==">document.addEventListener("DOMContentLoaded",()=>{if(!document.querySelector("#id-c5803a6e")){let e=document.createElement("a");e.href="#defaultCanvas0",e.id="id-104c3ca5",e.textContent="Skip to main content",e.style.position="absolute",e.style.top="-40px",e.style.left="10px",e.style.background="#fff",e.style.color="#000",e.style.padding="5px",e.style.zIndex="1004",e.style.transition="top 0.3s",e.addEventListener("focus",()=>{e.style.top="10px"}),e.addEventListener("blur",()=>{e.style.top="-40px"}),document.body.prepend(e)}let e=document.createElement("div"),t=(e.id="id-3eb3175e",e.role="progressbar",e.title="progressbar",e.style.position="fixed",e.style.top="0",e.style.left="0",e.style.width="0%",e.style.height="3px",e.style.background="#29d",e.style.zIndex="9999",e.style.transition="width 0.2s ease-in-out",document.body.appendChild(e),0),d=setInterval(()=>{(t+=10*Math.random())<90&&(e.style.width=t+"%")},200);window.addEventListener("load",()=>{clearInterval(d),e.style.width="100%",setTimeout(()=>{e.style.opacity="0"},500)})})</script></body></html>
          ```' > README.md

          # Buat LICENSE.txt
          echo 'MIT License

          Permission is hereby granted, free of charge, to any person obtaining a copy
          of this software and associated documentation files (the "Software"), to deal
          in the Software without restriction, including without limitation the rights
          to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
          copies of the Software, and to permit persons to whom the Software is
          furnished to do so, subject to the following conditions:

          The above copyright notice and this permission notice shall be included in all
          copies or substantial portions of the Software.

          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
          IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
          FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
          AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
          LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
          OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
          SOFTWARE.' > LICENSE.txt

      - name: Build Gem
        run: gem build hbd.gemspec

      - name: Setup Credentials
        run: |
          mkdir -p ~/.gem
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials

      - name: Publish to GitHub Packages
        run: gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Recreate and publish HBD gem" || echo "No changes to commit"
          git push || echo "No changes to push"
