name: Ruby Gem
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.6'
          
      - name: Create Gem Files
        run: |
          # Create directories
          mkdir -p lib/hbd/assets/javascripts
          
          # Create version file
          echo 'module HBD
            VERSION = "0.1.0"
          end' > lib/hbd/version.rb
          
          # Create main lib file
          echo 'require "hbd/version"

          module HBD
            class Error < StandardError; end
            
            def self.root
              File.expand_path "../..", __FILE__
            end
            
            def self.assets_path
              File.join root, "assets"
            end
          end' > lib/hbd.rb
          
          # Create fireworks.js
          echo 'let fireworks = [];
          let gravity;

          function setup() {
            createCanvas(windowWidth, windowHeight);
            colorMode(HSB);
            gravity = createVector(0, 0.2);
            stroke(255);
            strokeWeight(4);
            background(0);
          }

          function draw() {
            colorMode(RGB);
            background(0, 0, 0, 25);
            
            if (random(1) < 0.05) {
              fireworks.push(new Firework());
            }
            
            for (let i = fireworks.length - 1; i >= 0; i--) {
              fireworks[i].update();
              fireworks[i].show();
              
              if (fireworks[i].done()) {
                fireworks.splice(i, 1);
              }
            }
          }' > lib/hbd/assets/javascripts/fireworks.js
          
          # Create gemspec
          echo 'require_relative "lib/hbd/version"

          Gem::Specification.new do |spec|
            spec.name = "hbd"
            spec.version = HBD::VERSION
            spec.authors = ["${{ github.actor }}"]
            spec.email = ["${{ github.actor }}@users.noreply.github.com"]
            
            spec.summary = "HBD Animation with Fireworks"
            spec.description = "A Ruby gem that provides birthday fireworks animation"
            spec.homepage = "https://github.com/${{ github.repository }}"
            spec.license = "MIT"
            spec.required_ruby_version = ">= 3.1.0"
            
            spec.metadata = {
              "homepage_uri" => spec.homepage,
              "source_code_uri" => spec.homepage,
              "github_repo" => "ssh://github.com/${{ github.repository }}"
            }
            
            spec.files = Dir[
              "lib/**/*",
              "README.md",
              "LICENSE.txt"
            ]
            
            spec.add_development_dependency "rake", "~> 13.0"
            spec.add_development_dependency "rspec", "~> 3.0"
          end' > hbd.gemspec
          
          # Create Gemfile
          echo 'source "https://rubygems.org"
          gemspec' > Gemfile
          
          # Create README
          echo '# HBD Gem

          Ruby gem for birthday animation.

          ## Installation

          ```ruby
          source "https://rubygems.pkg.github.com/${{ github.repository_owner }}" do
            gem "hbd"
          end
          ```

          ## Usage

          Add to your HTML:

          ```html
          <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js"></script>
          <script src="/assets/javascripts/fireworks.js"></script>
          ```' > README.md
          
          # Create License
          echo 'MIT License

          Copyright (c) 2024 ${{ github.repository_owner }}

          Permission is hereby granted, free of charge, to any person obtaining a copy
          of this software and associated documentation files (the "Software"), to deal
          in the Software without restriction, including without limitation the rights
          to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
          copies of the Software, and to permit persons to whom the Software is
          furnished to do so, subject to the following conditions:

          The above copyright notice and this permission notice shall be included in all
          copies or substantial portions of the Software.

          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
          IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
          FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
          AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
          LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
          OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
          SOFTWARE.' > LICENSE.txt

      - name: Build Gem
        run: |
          gem build *.gemspec
          
      - name: Setup Credentials
        run: |
          mkdir -p ~/.gem
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          
      - name: Publish to GitHub Packages
        run: |
          gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Create and publish HBD gem" || echo "No changes to commit"
          git push || echo "No changes to push"
