name: Publish Ruby Gem HBD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.6'
          
      - name: Create Gem Files
        run: |
          # Set gem name and create directories
          GEM_NAME="hbd_animation"
          mkdir -p lib/${GEM_NAME}/assets/javascripts
          mkdir -p lib/${GEM_NAME}/assets/stylesheets
          
          # Create version file
          echo 'module HbdAnimation
            VERSION = "0.1.0"
          end' > lib/${GEM_NAME}/version.rb
          
          # Create main JavaScript file
          echo 'let fireworks = [];
          let gravity;

          function setup() {
            createCanvas(windowWidth, windowHeight);
            colorMode(HSB);
            gravity = createVector(0, 0.2);
            stroke(255);
            strokeWeight(4);
            background(0);
          }

          function draw() {
            colorMode(RGB);
            background(0, 0, 0, 25);
            
            if (random(1) < 0.05) {
              fireworks.push(new Firework());
            }
            
            for (let i = fireworks.length - 1; i >= 0; i--) {
              fireworks[i].update();
              fireworks[i].show();
              
              if (fireworks[i].done()) {
                fireworks.splice(i, 1);
              }
            }
          }

          class Particle {
            constructor(x, y, hu, firework) {
              this.pos = createVector(x, y);
              this.firework = firework;
              this.lifespan = 255;
              this.hu = hu;
              
              if (this.firework) {
                this.vel = createVector(0, random(-16, -8));
              } else {
                this.vel = p5.Vector.random2D();
                this.vel.mult(random(2, 10));
              }
              
              this.acc = createVector(0, 0);
            }

            applyForce(force) {
              this.acc.add(force);
            }
            
            update() {
              if (!this.firework) {
                this.vel.mult(0.9);
                this.lifespan -= 4;
              }
              
              this.vel.add(this.acc);
              this.pos.add(this.vel);
              this.acc.mult(0);
            }
            
            done() {
              return this.lifespan < 0;
            }
            
            show() {
              colorMode(HSB);
              
              if (!this.firework) {
                strokeWeight(2);
                stroke(this.hu, 255, 255, this.lifespan);
              } else {
                strokeWeight(4);
                stroke(this.hu, 255, 255);
              }
              
              point(this.pos.x, this.pos.y);
            }
          }

          class Firework {
            constructor() {
              this.hu = random(255);
              this.firework = new Particle(random(width), height, this.hu, true);
              this.exploded = false;
              this.particles = [];
            }
            
            done() {
              return this.exploded && this.particles.length === 0;
            }
            
            update() {
              if (!this.exploded) {
                this.firework.applyForce(gravity);
                this.firework.update();
                
                if (this.firework.vel.y >= 0) {
                  this.exploded = true;
                  this.explode();
                }
              }
              
              for (let i = this.particles.length - 1; i >= 0; i--) {
                this.particles[i].applyForce(gravity);
                this.particles[i].update();
                
                if (this.particles[i].done()) {
                  this.particles.splice(i, 1);
                }
              }
            }
            
            explode() {
              for (let i = 0; i < 100; i++) {
                const p = new Particle(this.firework.pos.x, this.firework.pos.y, this.hu, false);
                this.particles.push(p);
              }
            }
            
            show() {
              if (!this.exploded) {
                this.firework.show();
              }
              
              for (let i = 0; i < this.particles.length; i++) {
                this.particles[i].show();
              }
            }
          }' > lib/${GEM_NAME}/assets/javascripts/fireworks.js
          
          # Create main Ruby file
          echo 'require "hbd_animation/version"

          module HbdAnimation
            class Error < StandardError; end
            
            def self.assets_path
              File.expand_path("../hbd_animation/assets", __FILE__)
            end
            
            def self.javascript_path
              File.join(assets_path, "javascripts")
            end
            
            def self.stylesheets_path
              File.join(assets_path, "stylesheets")
            end
          end' > lib/${GEM_NAME}.rb
          
          # Create gemspec
          echo 'require_relative "lib/hbd_animation/version"

          Gem::Specification.new do |spec|
            spec.name = "hbd_animation"
            spec.version = HbdAnimation::VERSION
            spec.authors = ["${{ github.actor }}"]
            spec.email = ["${{ github.actor }}@users.noreply.github.com"]
            
            spec.summary = "HBD Animation with Fireworks"
            spec.description = "A Ruby gem that provides a beautiful fireworks animation for birthday celebrations"
            spec.homepage = "https://github.com/${{ github.repository }}"
            spec.license = "MIT"
            spec.required_ruby_version = ">= 3.1.0"
            
            spec.metadata = {
              "homepage_uri" => spec.homepage,
              "source_code_uri" => spec.homepage,
              "github_repo" => "ssh://github.com/${{ github.repository }}"
            }
            
            spec.files = Dir[
              "lib/**/*",
              "README.md",
              "LICENSE.txt"
            ]
            
            spec.require_paths = ["lib"]
            
            spec.add_development_dependency "rake", "~> 13.0"
            spec.add_development_dependency "rspec", "~> 3.0"
          end' > ${GEM_NAME}.gemspec
          
          # Create Gemfile
          echo 'source "https://rubygems.org"
          gemspec' > Gemfile
          
          # Create README
          echo '# HBD Animation

          A Ruby gem that provides beautiful fireworks animation for birthday celebrations using p5.js.

          ## Installation

          Add this line to your application'\''s Gemfile:

          ```ruby
          source "https://rubygems.pkg.github.com/${{ github.repository_owner }}" do
            gem "hbd_animation"
          end
          ```

          ## Usage

          Add this to your HTML:

          ```html
          <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js"></script>
          <script src="/assets/javascripts/fireworks.js"></script>
          ```

          ## Development

          After checking out the repo, run `bundle install` to install dependencies.

          ## License

          The gem is available as open source under the terms of the MIT License.' > README.md

      - name: Build Gem
        run: |
          gem build *.gemspec
          
      - name: Setup Credentials
        run: |
          mkdir -p ~/.gem
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          
      - name: Publish to GitHub Packages
        run: |
          gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Create and publish HBD animation gem" || echo "No changes to commit"
          git push || echo "No changes to push"
