name: Setup Ruby Gem
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.6'
          
      - name: Create Gem Structure
        run: |
          # Set gem name
          GEM_NAME="HBD"
          AUTHOR_NAME="${{ github.actor }}"
          AUTHOR_EMAIL="${{ github.actor }}@users.noreply.github.com"
          
          # Create base directories
          mkdir -p lib/${GEM_NAME}
          mkdir -p spec
          mkdir -p bin
          
          # Create version.rb
          echo '# frozen_string_literal: true

          module MyExampleGem
            VERSION = "0.1.0"
          end' > lib/${GEM_NAME}/version.rb
          
          # Create main lib file
          echo '# frozen_string_literal: true

          require_relative "my_example_gem/version"

          module MyExampleGem
            class Error < StandardError; end
            # Your code goes here...
          end' > lib/${GEM_NAME}.rb
          
          # Create gemspec
          echo '# frozen_string_literal: true

          require_relative "lib/my_example_gem/version"

          Gem::Specification.new do |spec|
            spec.name = "HBD"
            spec.version = MyExampleGem::VERSION
            spec.authors = ["'${AUTHOR_NAME}'"]
            spec.email = ["'${AUTHOR_EMAIL}'"]

            spec.summary = "HBD"
            spec.description = "HBD"
            spec.homepage = "https://github.com/${{ github.repository }}"
            spec.license = "MIT"
            spec.required_ruby_version = ">= 3.1.0"

            spec.metadata["homepage_uri"] = spec.homepage
            spec.metadata["source_code_uri"] = spec.homepage

            spec.files = Dir["lib/**/*", "README.md"]
            spec.require_paths = ["lib"]

            spec.add_development_dependency "rake", "~> 13.0"
            spec.add_development_dependency "rspec", "~> 3.0"
          end' > ${GEM_NAME}.gemspec
          
          # Create Gemfile
          echo 'source "https://rubygems.org"
          gemspec' > Gemfile
          
          # Create Rakefile
          echo 'require "bundler/gem_tasks"
          require "rspec/core/rake_task"

          RSpec::Core::RakeTask.new(:spec)
          task default: :spec' > Rakefile
          
          # Create README
          echo "# MyExampleGem

          Welcome to your new gem! This gem was created using GitHub Actions.

          ## Installation

          Add this line to your application's Gemfile:

          \`\`\`ruby
          gem 'my_example_gem'
          \`\`\`

          ## Usage

          TODO: Write usage instructions here

          ## Development

          After checking out the repo, run \`bundle install\` to install dependencies.

          ## License

          The gem is available as open source under the terms of the MIT License." > README.md
          
          # Create basic spec files
          mkdir -p spec/${GEM_NAME}
          echo 'require "spec_helper"

          RSpec.describe MyExampleGem do
            it "has a version number" do
              expect(MyExampleGem::VERSION).not_to be nil
            end
          end' > spec/${GEM_NAME}_spec.rb
          
          echo 'require "my_example_gem"

          RSpec.configure do |config|
            config.example_status_persistence_file_path = ".rspec_status"
            config.disable_monkey_patching!
            config.expect_with :rspec do |c|
              c.syntax = :expect
            end
          end' > spec/spec_helper.rb

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Initial gem setup" || echo "No changes to commit"
          git push || echo "No changes to push"
